#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : atelier4.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Mar 21 15:49:12 -0400 2023
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: atelier4.sh [-help]
# usage: atelier4.sh [-lib_map_path]
# usage: atelier4.sh [-noclean_files]
# usage: atelier4.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'atelier4.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm lib_cdc_v1_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_24 axi_vdma_v6_3_10 xil_defaultlib proc_sys_reset_v5_0_13 axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 axi_lite_ipif_v3_0_4 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_11 v_vscaler_v1_1_0 v_hscaler_v1_1_0 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_22 axis_subset_converter_v1_1_22 interrupt_control_v3_1_4 axi_gpio_v2_0_24 axis_data_fifo_v2_0_4 xlslice_v1_0_2 v_tc_v6_2_1 xlconstant_v1_1_7)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "atelier4.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_10 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_axi_vdma_0_0/sim/atelier4_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_clk_wiz_0_0/atelier4_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_clk_wiz_0_0/atelier4_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_proc_sys_reset_0_0/sim/atelier4_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_processing_system7_0_0/sim/atelier4_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d57c/src/ClockGen.vhd" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d57c/src/SyncAsync.vhd" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d57c/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d57c/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d57c/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d57c/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d57c/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_rgb2dvi_0_0/sim/atelier4_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/c:/Users/wpepi/projet/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/atelier4_smartconnect_0_0_sim_netlist.v" \
    "$ref_dir/c:/Users/wpepi/projet/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/atelier4_smartconnect_0_1_sim_netlist.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_axi4s_vid_out_0_0/sim/atelier4_v_axi4s_vid_out_0_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_0/bd_0837_smartconnect_0_0_sim_netlist.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_AXIvideo2MultiPixStream.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_Block_split4_proc.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_CTRL_s_axi.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_fifo_w8_d2_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_fifo_w8_d3_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_fifo_w10_d2_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_fifo_w10_d4_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_fifo_w11_d2_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_fifo_w24_d16_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_fifo_w32_d4_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_hls_deadlock_detection_unit.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_mac_muladd_8ns_16s_13ns_24_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_mac_muladd_8ns_16s_24s_25_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_mac_muladd_8ns_16s_25s_26_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_mac_muladd_8ns_16s_26s_26_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_mac_muladd_8ns_16s_26s_27_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_mac_muladd_8ns_16s_27s_27_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_MultiPixStream2AXIvideo.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_reg_unsigned_short_s.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_regslice_both.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_start_for_AXIvideo2MultiPixStream_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_start_for_MultiPixStream2AXIvideo_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_start_for_v_vcresampler_core_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_v_vcresampler_core.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_v_vcresampler_core_linebuf_c_val_V_2.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_v_vcresampler_core_linebuf_y_val_V_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_v_vcresampler_core_linebuf_y_val_V_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_vscale_core_polyphase.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_vscale_core_polyphase_FiltCoeff_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_vscale_core_polyphase_LineBuf_val_V_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog/bd_0837_vsc_0_v_vscaler.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vscaler_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/v_vscaler_v1_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/sim/bd_0837_vsc_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_AXIvideo2MultiPixStream.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_Block_split1_proc.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_Block_split12_proc.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_CTRL_s_axi.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_fifo_w1_d2_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_fifo_w1_d6_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_fifo_w1_d7_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_fifo_w8_d2_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_fifo_w24_d16_S.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_hls_deadlock_detection_unit.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_hscale_core_polyphase.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_hscale_core_polyphase_FiltCoeff_0_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_hscale_polyphase.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_mac_muladd_8ns_16s_13ns_24_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_mac_muladd_8ns_16s_24s_25_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_mac_muladd_8ns_16s_25s_26_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_mac_muladd_8ns_16s_26s_26_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_mac_muladd_8ns_16s_26s_27_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_mac_muladd_8ns_16s_27s_27_4_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_MultiPixStream2AXIvideo.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_MultiPixStream2AXIvideo_mapComp.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_mux_32_8_1_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_mux_83_8_1_1.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_reg_ap_uint_9_s.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_regslice_both.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_start_for_AXIvideo2MultiPixStream_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_start_for_Block_split1_proc_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_start_for_MultiPixStream2AXIvideo_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_start_for_v_hcresampler_core_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_start_for_v_hscaler_entry32_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_start_for_v_vcresampler_core_U0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_v_hcresampler_core.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_v_hcresampler_core26.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_v_hscaler_entry4.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_v_hscaler_entry32.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_v_vcresampler_core.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_v_vcresampler_core_linebuf_c_val_V_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_v_vcresampler_core_linebuf_y_val_V_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog/bd_0837_hsc_0_v_hscaler.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_hscaler_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/v_hscaler_v1_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/sim/bd_0837_hsc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tdata_bd_0837_input_size_set_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tuser_bd_0837_input_size_set_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tstrb_bd_0837_input_size_set_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tkeep_bd_0837_input_size_set_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tid_bd_0837_input_size_set_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tdest_bd_0837_input_size_set_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tlast_bd_0837_input_size_set_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/69d9/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/top_bd_0837_input_size_set_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/sim/bd_0837_input_size_set_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_4/sim/bd_0837_rst_axis_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_5/sim/bd_0837_reset_sel_axis_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_6/sim/bd_0837_axis_register_slice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/abd4/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_7/sim/bd_0837_axis_fifo_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_8/sim/bd_0837_xlslice_0_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_9/sim/bd_0837_xlslice_1_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/atelier4_v_proc_ss_0_0_sim_netlist.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_v_tc_0_0/sim/atelier4_v_tc_0_0.vhd" \
    "$ref_dir/../../../bd/atelier4/ipshared/7229/hdl/pixelDataToVideoStream_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/atelier4/ipshared/7229/hdl/pixelDataToVideoStream_v1_0.vhd" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_pixelDataToVideoStre_0_3/sim/atelier4_pixelDataToVideoStre_0_3.vhd" \
    "$ref_dir/../../../bd/atelier4/ipshared/0125/hdl/InstructionRegister_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/atelier4/ipshared/0125/hdl/InstructionRegister_v1_0.vhd" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_InstructionRegister_0_1/sim/atelier4_InstructionRegister_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_xlconstant_4_0/sim/atelier4_xlconstant_4_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_xlslice_0_0/sim/atelier4_xlslice_0_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_xlslice_0_1/sim/atelier4_xlslice_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_colorRegister_0_0/sim/atelier4_colorRegister_0_0.vhd" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_BackgroundManager_0_0/sim/atelier4_BackgroundManager_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/d0f7" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/verilog" +incdir+"$ref_dir/../../../../s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_xlslice_2_0/sim/atelier4_xlslice_2_0.v" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_xlslice_2_1/sim/atelier4_xlslice_2_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_InstructionDecoder_0_0/sim/atelier4_InstructionDecoder_0_0.vhd" \
    "$ref_dir/../../../bd/atelier4/ip/atelier4_TileBufferBackground_0_0/sim/atelier4_TileBufferBackground_0_0.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.atelier4 xil_defaultlib.glbl -o atelier4_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./atelier4_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./atelier4.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key atelier4_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc atelier4_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./atelier4.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: atelier4.sh [-help]\n\
Usage: atelier4.sh [-lib_map_path]\n\
Usage: atelier4.sh [-reset_run]\n\
Usage: atelier4.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
